### ISSUE TITLE
세션만료가 제대로 이루어지지 않습니다. 

### ISSUE THREAD

**Issue by 8954sood** [2023-DGSW-FLY/Android_Hook#36]
java.lang.IllegalStateException: Cannot invoke setValue on a background thread
                                                                                                    	at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:487)
                                                                                                    	at androidx.lifecycle.LiveData.setValue(LiveData.java:306)
                                                                                                    	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                                                                                                    	at com.innosync.hook.base.BaseViewModel.onFailures-KWTtemM(BaseViewModel.kt:24)

**Comment by 8954sood** [comment]
세션이 만료되었을 떄 fragment에서 로그인 화면으로 이동시켜야하지만, 에러 코드에서 반환하는 메세지가 정의된 메세지와 달라 이동하지 않고 앱이 꺼지는 현상을 막았습니다.
